import test from 'node:test';import assert from 'node:assert/strict';import {OneHandController} from '../src/one-hand-controller.mjs';
const hand=(o={})=>({id:'Right',indexFlex:.2,middleFlex:.2,roll:0,wristX:.5,wristY:.5,pointX:.4,pointY:.4,open:false,pointing:false,...o});
const fresh=()=>{const c=new OneHandController();c.calibrate([hand()],0);return c;};
function walk(c,start=33,o={},n=16){let result;for(let i=0;i<n;i++)result=c.update([hand({indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1,...o})],start+i*33);return result;}
test('finger rhythm moves forward and lowering hand reverses',()=>{const c=fresh();assert(walk(c).forward>.1);assert(walk(c,561,{wristY:.68}).forward<-.1);assert(walk(c,1089,{wristY:.5}).forward>.1);});
test('hand position steers with steps and neutral stops steering',()=>{const c=fresh();assert(walk(c,33,{wristX:.7}).turn<-.2);assert(walk(c,561,{wristX:.3}).turn>.2);assert.equal(walk(c,1089,{wristX:.5},32).turn,0);});
test('held tilt and position without finger rhythm never turn or walk',()=>{const c=fresh();for(let t=33;t<1000;t+=33){const s=c.update([hand({roll:1,wristX:.8})],t);assert.equal(s.turn,0);assert.equal(s.forward,0);assert.equal(s.headingTarget,null);}});
test('stopping fingers stops yaw even with hand held far from neutral',()=>{const c=fresh();walk(c,33,{wristX:.7});let s;for(let t=561;t<1000;t+=33)s=c.update([hand({wristX:.7,indexFlex:.4,middleFlex:.1})],t);assert.equal(s.turn,0);assert.equal(s.forward,0);});
test('open palm stops and recenters, tracking identity change resets position',()=>{const c=fresh();walk(c,33,{wristX:.7});const s=c.update([hand({open:true,wristX:.7})],561);assert.equal(s.turn,0);assert.equal(s.forward,0);assert.equal(c.anchor.x,.7);assert.equal(c.update([hand({id:'Left',wristX:.2})],594).turn,0);assert.equal(c.anchor.x,.2);});
test('point dwell sprays aligned with cursor; UI and stale input revoke authority',()=>{const c=fresh();let s;for(let t=33;t<=396;t+=33)s=c.update([hand({pointing:true})],t);assert.equal(s.spraying,true);assert(Math.abs(s.aim.x-(.85-.4)/.7)<1e-10);assert.equal(c.read(410,{overUi:true}).spraying,false);assert.equal(c.read(617).spraying,false);assert.equal(c.read(617).turn,0);});
