import test from 'node:test';import assert from 'node:assert/strict';import {OneHandController,withNavigationPoint} from '../src/one-hand-controller.mjs';
const hand=(o={})=>({id:'Right',indexFlex:.2,middleFlex:.2,roll:0,navX:.5,navY:.5,wristX:.5,wristY:.9,pointX:.4,pointY:.4,steerX:0,open:false,pointing:false,fist:false,thumbSpread:0,thumbStraight:0,...o});
const fresh=()=>{const c=new OneHandController();c.calibrate([hand()],0);return c;};
function walk(c,start=40,{reverse=false,interval=80,pointing=false}={}){let s;for(let i=0;i<8;i++)s=c.update([hand({indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1,thumbSpread:reverse?.7:0,thumbStraight:reverse?.9:0,pointing})],start+i*interval);return s;}
test('translation requires finger flex motion but not perfect phase alternation',()=>{const c=fresh();assert.equal(c.update([hand({navY:.2,wristY:.1})],40).forward,0);assert(c.update([hand({indexFlex:.225,middleFlex:.2})],120).forward>0);assert(c.update([hand({indexFlex:.25,middleFlex:.2})],200).forward>0);});
test('thumb gesture reverses active finger walking',()=>{const c=fresh();assert(walk(c).forward>0);assert(walk(c,800,{reverse:true}).forward<0);});
test('frozen neutral fingers stop instead of lingering',()=>{const c=fresh();walk(c);for(let t=700;t<=1200;t+=100)c.update([hand()],t);assert.equal(c.read(1200).forward,0);});
test('slow 4Hz tracking carries walking between samples then fades by 450ms',()=>{const c=fresh();let s;for(let i=0;i<8;i++)s=c.update([hand({indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1})],250+i*250);assert(s.forward>0);const last=250+7*250;assert(c.read(last+340).forward>0);assert.equal(c.read(last+450).forward,0);});
test('pointing direction steers while stationary and raw neutral stops immediately',()=>{const c=fresh();let s;for(let t=40;t<440;t+=40)s=c.update([hand({steerX:.5})],t);assert(s.turn>.8);assert.equal(s.forward,0);s=c.update([hand({steerX:0})],480);assert.equal(s.turn,0);});
test('absolute wrist and navigation translation do not affect steering',()=>{const c=fresh();for(let t=40;t<600;t+=40){const s=c.update([hand({wristX:t%80?.05:.95,wristY:.1,navX:.8,navY:.2,steerX:0})],t);assert.equal(s.turn,0);assert.equal(s.forward,0);}});
test('handedness label flicker preserves steering neutral and walking',()=>{const c=fresh();const neutral=c.steerNeutral;let s;for(let i=0;i<8;i++)s=c.update([hand({id:i%2?'Left':'Right',indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1,steerX:.3})],40+i*80);assert(s.forward>0);assert(s.turn>0);assert.equal(c.steerNeutral,neutral);});
test('open palm recentres steering once and fist, UI, and loss stop',()=>{const c=fresh();walk(c);c.update([hand({open:true,steerX:.3})],700);assert.equal(c.steerNeutral,.3);c.update([hand({open:true,steerX:-.3})],750);assert.equal(c.steerNeutral,.3);assert.equal(c.update([hand({fist:true})],800).forward,0);walk(c,900);assert.equal(c.update([hand()],1600,{overUi:true}).forward,0);walk(c,1700);assert.equal(c.update([],2400).forward,0);});
test('active finger walking cannot become hose; quiet pointing dwell stays spraying',()=>{const c=fresh();for(let i=0;i<10;i++){const s=c.update([hand({pointing:true,indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1})],40+i*80);assert.equal(s.spraying,false);}assert.equal(c.update([hand({pointing:true,indexFlex:.2,middleFlex:.2})],900).spraying,false);assert.equal(c.update([hand({pointing:true,indexFlex:.2,middleFlex:.2})],940).spraying,false);assert.equal(c.update([hand({pointing:true,indexFlex:.2,middleFlex:.2})],1300).spraying,true);for(let i=1;i<=10;i++)assert.equal(c.update([hand({pointing:true,indexFlex:.2,middleFlex:.2})],1300+i*40).spraying,true);assert.equal(c.read(1930).spraying,false);assert.equal(c.read(2140).forward,0);});
function landmarkFixture({shift=0,scale=1,mirror=1,thumb='out'}={}){const p=Array.from({length:21},()=>({x:shift,y:shift,z:shift})),at=(x,y,z=0)=>({x:shift+mirror*x*scale,y:shift+y*scale,z:shift+z*scale});p[5]=at(.4,.5);p[6]=at(.55,.42,.03);p[9]=at(.5,.55);p[10]=at(.65,.47,.03);p[13]=at(.6,.56);p[17]=at(.7,.55);p[2]=at(.37,.58);if(thumb==='out'){p[3]=at(.27,.56);p[4]=at(.16,.54);}else{p[3]=at(.36,.53);p[4]=at(.4,.49);}return p;}
test('proximal pointing feature is translation and scale invariant with mirrored signs',()=>{const a=withNavigationPoint(hand(),landmarkFixture());const b=withNavigationPoint(hand(),landmarkFixture({shift:.1,scale:.5}));const mirrored=withNavigationPoint(hand(),landmarkFixture({mirror:-1}));assert(Math.abs(a.steerX-b.steerX)<1e-12);assert(a.steerX<0);assert(mirrored.steerX>0);});
test('thumb reverse geometry distinguishes extended outward from tucked and is mirror/scale invariant',()=>{const out=withNavigationPoint(hand(),landmarkFixture()),scaled=withNavigationPoint(hand(),landmarkFixture({shift:.1,scale:.5,mirror:-1})),tucked=withNavigationPoint(hand(),landmarkFixture({thumb:'tucked'}));assert(out.thumbSpread>.55);assert(out.thumbStraight>.75);assert(Math.abs(out.thumbSpread-scaled.thumbSpread)<1e-12);assert(Math.abs(out.thumbStraight-scaled.thumbStraight)<1e-12);assert(tucked.thumbSpread<.35||tucked.thumbStraight<.55);});
test('reverse never creates movement and clears on stopping',()=>{const c=fresh();for(let t=40;t<500;t+=40)c.update([hand({thumbSpread:.8,thumbStraight:.9})],t);assert.equal(c.read(500).forward,0);walk(c,600,{reverse:true});assert(c.read(1200).forward<0);c.update([hand({fist:true})],1250);assert.equal(c.diagnostics(1250).reverse,false);});
test('reverse requires a continuous hold and invalid thumb geometry revokes it',()=>{const c=fresh();walk(c);c.update([hand({indexFlex:.4,middleFlex:.1,thumbSpread:.8,thumbStraight:.9})],700);c.update([hand({indexFlex:.1,middleFlex:.4,thumbSpread:0,thumbStraight:0})],800);c.update([hand({indexFlex:.4,middleFlex:.1,thumbSpread:.8,thumbStraight:.9})],900);assert.equal(c.diagnostics(900).reverse,false);c.update([hand({indexFlex:.1,middleFlex:.4,thumbSpread:.8,thumbStraight:.9})],1100);assert.equal(c.diagnostics(1100).reverse,true);const invalid=hand({indexFlex:.4,middleFlex:.1});delete invalid.thumbSpread;delete invalid.thumbStraight;c.update([invalid],1200);assert.equal(c.diagnostics(1200).reverse,false);});
test('diagnostics expose the revised control contract',()=>{const d=fresh().diagnostics(0);assert.equal(d.control,'finger-walk-point-steer');assert.equal(d.steerNeutral,0);assert.equal(d.steerX,0);assert.equal(d.reverse,false);});
test('extra hand and array reordering preserve the original one-hand walker',()=>{const c=fresh(),other=hand({id:'Left',navX:.9,steerX:-.9});let s;for(let i=0;i<8;i++){const owner=hand({id:i%2?'Left':'Right',indexFlex:i%2?.1:.4,middleFlex:i%2?.4:.1,steerX:.3});s=c.update(i%2?[other,owner]:[owner,other],40+i*80);assert.equal(c.point.x,.5);}assert(s.forward>0);assert(s.turn>0);assert.equal(c.steerNeutral,0);});
