import '@babylonjs/loaders/glTF';
import {AbstractMesh,Bone,Matrix,PBRMaterial,Quaternion,Scene,SceneLoader,Space,TransformNode,Vector3,VertexBuffer} from '@babylonjs/core';
import {SelectedSkinVertices} from './foot-skinning';

export type AstronautPose={left:number;right:number;leftLift:number;rightLift:number;stride:number;cadence:number;leftToe?:number;rightToe?:number;articulated?:boolean;source:'measured'|'distance'|'neutral'};
export type GroundedFoot={local:{x:number;y:number;z:number};worldAnchor?:{x:number;y:number;z:number}|null;planted:boolean;toe:number;groundY?:number;yaw?:number};
export type GroundedFeet={left:GroundedFoot;right:GroundedFoot};
export type GroundedMotionContext={dt:number;active:boolean;yawRate?:number;speed?:number;phase?:number;cycle?:number;run?:number;supportSide?:'left'|'right'};
type JointSnapshot={hip:{x:number;y:number;z:number};knee:{x:number;y:number;z:number};ankle:{x:number;y:number;z:number};toe?:{x:number;y:number;z:number};boot:{x:number;y:number;z:number;minY:number;radius:number}};
const neutral:AstronautPose={left:0,right:0,leftLift:0,rightLift:0,stride:0,cadence:0,source:'neutral'};
export const HOSE_ANCHOR={x:.08,y:1.6,z:.28} as const;

export function createAstronaut(scene:Scene,parent:TransformNode,options:{referenceSkinning?:boolean}={}){
 const visual=new TransformNode('astronaut visual',scene);visual.parent=parent;
 let loadState:'loading'|'ready'|'error'='loading',loadError='',latestPose:AstronautPose=neutral,root:AbstractMesh|null=null,meshes:AbstractMesh[]=[];
 let skeletonRoot:TransformNode|null=null,bones=new Map<string,Bone>(),rest=new Map<string,Quaternion>(),modelScale=1;
 let soleOffsets=[new Vector3(0,-.2,.12),new Vector3(0,-.2,.12)],legLengths=[[.51,.502],[.51,.502]],ikStatus:any={ready:false,feet:[]},filteredPelvisDrop=0,wholeBodySpeed=0;
 let neutralFootAxes=[{x:Vector3.Right(),y:Vector3.Up(),z:Vector3.Forward()},{x:Vector3.Right(),y:Vector3.Up(),z:Vector3.Forward()}],skinDirty=true;
 let loadedSkeletons:ReturnType<Bone['getSkeleton']>[]=[];const footVertices:{mesh:AbstractMesh;indices:number[];sampler?:SelectedSkinVertices}[][]=[[],[]],skinnedFootPoints:{mesh:AbstractMesh;point:Vector3}[][]=[[],[]];let skinMesh:AbstractMesh|null=null;
 let analyticJoints=poseTargets(neutral),resolveReady:()=>void=()=>{},rejectReady:(error:unknown)=>void=()=>{};
 const ready=new Promise<void>((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});

 function poseTargets(pose:AstronautPose){
  return [-1,1].map((side,index)=>{const phase=index===0?pose.left:pose.right,lift=index===0?pose.leftLift:pose.rightLift,travel=(pose.source==='measured'?phase:phase*pose.stride)*.34,hip={x:side*.2,y:1.08,z:0},ankle={x:side*.2,y:.27+lift*.3,z:travel},l1=.47,l2=.47,dy=ankle.y-hip.y,dz=ankle.z-hip.z,d=Math.max(.001,Math.min(l1+l2-.003,Math.hypot(dy,dz))),uy=dy/d,uz=dz/d,along=(l1*l1-l2*l2+d*d)/(2*d),bend=Math.sqrt(Math.max(0,l1*l1-along*along)),knee={x:hip.x,y:hip.y+uy*along+uz*bend,z:hip.z+uz*along-uy*bend};return {hip,knee,ankle,boot:{x:ankle.x,y:.19+lift*.3,z:travel+.12,minY:.063+lift*.3,radius:.45}};});
 }
 const bone=(name:string)=>bones.get(`mixamorig:${name}`);
 function rotate(name:string,angle:number,axis=Vector3.Right()){const value=bone(name),base=rest.get(name),node=value?.getTransformNode();if(node&&base){node.rotationQuaternion=base.multiply(Quaternion.RotationAxis(axis,angle));skinDirty=true;}}
 function rotateCompound(name:string,rotations:{axis:Vector3;angle:number}[]){const value=bone(name),base=rest.get(name),node=value?.getTransformNode();if(node&&base){node.rotationQuaternion=rotations.reduce((result,item)=>result.multiply(Quaternion.RotationAxis(item.axis,item.angle)),base.clone());skinDirty=true;}}
 function rotateOnWorldAxis(name:string,baseAdjustment:Quaternion,angle:number,worldAxis:Vector3){const value=bone(name),base=rest.get(name),node=value?.getTransformNode(),parentNode=node?.parent as TransformNode|null;if(!node||!base||!parentNode)return;parentNode.computeWorldMatrix(true);const inverse=Matrix.Identity();parentNode.getWorldMatrix().invertToRef(inverse);const axis=Vector3.TransformNormal(worldAxis,inverse).normalize();node.rotationQuaternion=Quaternion.RotationAxis(axis,angle).multiply(base.multiply(baseAdjustment));skinDirty=true;}
 function applyUpperBody(motion?:GroundedMotionContext){const active=!!motion?.active,elapsed=Math.max(0,Math.min(.05,motion?.dt??0)),targetSpeed=active?Math.max(0,motion?.speed??0):0;if(!active)wholeBodySpeed=0;else wholeBodySpeed+=(targetSpeed-wholeBodySpeed)*(1-Math.exp(-elapsed/.1));const run=Math.max(0,Math.min(1,motion?.run??0)),weight=Math.min(1,wholeBodySpeed/.65),wave=-Math.cos(motion?.cycle??0)*weight,armAmplitude=(.22+run*.28)*Math.min(1,wholeBodySpeed/1.4),elbowBend=(.16+run*.9)*weight,turn=Math.max(-1,Math.min(1,motion?.yawRate??0)),forwardLean=run*.11*weight,twist=-wave*(.045+run*.035)-turn*.025*weight,bodyRight=yawAxis(Vector3.Right(),parent.rotation.y);rotateCompound('Spine1',[{axis:Vector3.Right(),angle:-forwardLean},{axis:Vector3.Up(),angle:twist}]);prepare();const lowered=Quaternion.RotationAxis(Vector3.Right(),1.2);rotateOnWorldAxis('LeftArm',lowered,wave*armAmplitude,bodyRight);rotateOnWorldAxis('RightArm',lowered,-wave*armAmplitude,bodyRight);prepare();rotateOnWorldAxis('LeftForeArm',Quaternion.Identity(),elbowBend*(.75+.25*Math.max(0,wave)),bodyRight);rotateOnWorldAxis('RightForeArm',Quaternion.Identity(),elbowBend*(.75+.25*Math.max(0,-wave)),bodyRight);prepare();rotateOnWorldAxis('LeftHand',Quaternion.Identity(),wave*.05,bodyRight);rotateOnWorldAxis('RightHand',Quaternion.Identity(),-wave*.05,bodyRight);return {cycle:motion?.cycle??0,speedEnvelope:wholeBodySpeed,run,weight,armWave:wave,armAmplitude,elbowBend,forwardLean,twist};}
 function refreshSkinnedFeet(){
  if(!skinDirty||loadState!=='ready')return;prepare();const references=new Map<AbstractMesh,ReturnType<AbstractMesh['getPositionData']>>();for(let side=0;side<2;side++){skinnedFootPoints[side]=[];for(const group of footVertices[side]){let data:any;if(options.referenceSkinning){if(!references.has(group.mesh))references.set(group.mesh,group.mesh.getPositionData(true));const all=references.get(group.mesh);if(all)for(const vertex of group.indices)skinnedFootPoints[side].push({mesh:group.mesh,point:Vector3.FromArray(all,vertex*3)});continue;}data=group.sampler?.update();if(data)for(let i=0;i<group.indices.length;i++)skinnedFootPoints[side].push({mesh:group.mesh,point:Vector3.FromArray(data,i*3)});}}skinDirty=false;
 }
 function verifyFootSkinning(){prepare();return Math.max(0,...footVertices.flat().map(group=>group.sampler?.maxReferenceError()??Infinity));}
 function applyBones(pose:AstronautPose){
  if(loadState!=='ready')return;
  for(let index=0;index<2;index++){
   const side=index===0?'Left':'Right',phase=index===0?pose.left:pose.right,lift=index===0?pose.leftLift:pose.rightLift,travel=(pose.source==='measured'?phase:phase*pose.stride)*.52,l1=.51,l2=.502,targetY=-(l1+l2-lift*.43),distance=Math.max(.001,Math.min(l1+l2-.002,Math.hypot(targetY,travel))),direction=Math.atan2(-travel,-targetY),hipBend=Math.acos(Math.max(-1,Math.min(1,(l1*l1+distance*distance-l2*l2)/(2*l1*distance)))),kneeBend=Math.PI-Math.acos(Math.max(-1,Math.min(1,(l1*l1+l2*l2-distance*distance)/(2*l1*l2))));
   rotate(`${side}UpLeg`,-direction+hipBend);rotate(`${side}Leg`,-kneeBend);const toe=index===0?(pose.leftToe??0):(pose.rightToe??0);
   rotate(`${side}Foot`,direction-hipBend+kneeBend*.75+toe*.18);rotate(`${side}ToeBase`,toe*.32);
  }
  applyUpperBody();prepare();refreshSkinnedFeet();
 }
 function applyPose(pose:AstronautPose){latestPose=pose;analyticJoints=poseTargets(pose);visual.position.set((pose.rightLift-pose.leftLift)*.02*pose.stride,(pose.leftLift+pose.rightLift)*.012*pose.stride,0);visual.rotation.set(0,0,(pose.rightLift-pose.leftLift)*.025*pose.stride);applyBones(pose);return snapshot();}
 function prepare(){for(const skeleton of loadedSkeletons){skeleton.prepare(true);skeleton.computeAbsoluteMatrices(true);}}
 function nodePoint(name:string){const node=bone(name)?.getTransformNode();if(!node)return null;node.computeWorldMatrix(true);return node.getAbsolutePosition().clone();}
 function alignBone(name:string,currentFrom:Vector3,currentTo:Vector3,desiredTo:Vector3){
  const node=bone(name)?.getTransformNode(),base=rest.get(name);if(!node||!base)return;
  const fromWorld=currentTo.subtract(currentFrom),toWorld=desiredTo.subtract(currentFrom);if(fromWorld.lengthSquared()<1e-8||toWorld.lengthSquared()<1e-8)return;
  const parentNode=node.parent as TransformNode|null,inverseParent=Matrix.Identity();if(parentNode)parentNode.getWorldMatrix().invertToRef(inverseParent);
  const from=Vector3.TransformNormal(fromWorld,inverseParent).normalize(),to=Vector3.TransformNormal(toWorld,inverseParent).normalize(),localDelta=new Quaternion();Quaternion.FromUnitVectorsToRef(from,to,localDelta);
  node.rotationQuaternion=localDelta.multiply(node.rotationQuaternion??base);skinDirty=true;
 }
 function yawAxis(axis:Vector3,yaw:number){const cos=Math.cos(yaw),sin=Math.sin(yaw);return new Vector3(axis.x*cos+axis.z*sin,axis.y,-axis.x*sin+axis.z*cos);}
 // Forest Crew additive pose: keep Hand Walk's grounded body/legs, then bring
 // both hands onto a nozzle grip. The nozzle mesh uses the same local anchor.
 function applyHosePose(){
  const nozzleLocal=new Vector3(HOSE_ANCHOR.x,HOSE_ANCHOR.y,HOSE_ANCHOR.z),toWorld=(point:Vector3)=>{const cos=Math.cos(parent.rotation.y),sin=Math.sin(parent.rotation.y);return new Vector3(parent.position.x+point.x*cos+point.z*sin,parent.position.y+point.y+visual.position.y,parent.position.z-point.x*sin+point.z*cos);};
  const nozzle=toWorld(nozzleLocal);
  if(loadState!=='ready'){const status={ready:false,nozzle:{local:{x:nozzleLocal.x,y:nozzleLocal.y,z:nozzleLocal.z},world:{x:nozzle.x,y:nozzle.y,z:nozzle.z}},hands:[]};ikStatus={...ikStatus,hose:status};return status;}
  const poses=[
   {side:'Left',outward:-1,grip:toWorld(new Vector3(.02,1.62,.24))},
   {side:'Right',outward:1,grip:toWorld(new Vector3(.14,1.58,.32))},
  ];
  const solves:any[]=[];
  for(const pose of poses){
   const shoulder=nodePoint(`${pose.side}Arm`),elbow=nodePoint(`${pose.side}ForeArm`),hand=nodePoint(`${pose.side}Hand`);
   if(!shoulder||!elbow||!hand){solves.push({side:pose.side.toLowerCase(),target:pose.grip,reach:null});continue;}
   const upper=Vector3.Distance(shoulder,elbow),lower=Vector3.Distance(elbow,hand),toward=pose.grip.subtract(shoulder),targetDistance=toward.length(),distance=Math.max(.001,Math.min(upper+lower-.005,targetDistance)),direction=toward.scale(1/Math.max(.001,targetDistance));
   const along=(upper*upper-lower*lower+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,upper*upper-along*along)),bodyRight=yawAxis(Vector3.Right(),parent.rotation.y),preferred=bodyRight.scale(pose.outward).add(new Vector3(0,-.35,0)),pole=preferred.subtract(direction.scale(Vector3.Dot(preferred,direction)));
   if(pole.lengthSquared()<1e-6)pole.copyFrom(Vector3.Cross(direction,Vector3.Up()));pole.normalize();
   const elbowTarget=shoulder.add(direction.scale(along)).add(pole.scale(height));alignBone(`${pose.side}Arm`,shoulder,elbow,elbowTarget);prepare();
   const elbowAfter=nodePoint(`${pose.side}ForeArm`),handAfter=nodePoint(`${pose.side}Hand`);if(elbowAfter&&handAfter)alignBone(`${pose.side}ForeArm`,elbowAfter,handAfter,pose.grip);prepare();
   solves.push({side:pose.side.toLowerCase(),target:pose.grip,reach:{upper,lower,total:upper+lower,targetDistance,clamped:targetDistance>upper+lower-.005,shoulder:{x:shoulder.x,y:shoulder.y,z:shoulder.z}},elbowTarget});
  }
  const hands=solves.map(solve=>{const hand=nodePoint(`${solve.side[0].toUpperCase()+solve.side.slice(1)}Hand`);return {side:solve.side,target:{x:solve.target.x,y:solve.target.y,z:solve.target.z},actual:hand&&{x:hand.x,y:hand.y,z:hand.z},error:hand?Vector3.Distance(hand,solve.target):null,reach:solve.reach,elbowTarget:solve.elbowTarget&&{x:solve.elbowTarget.x,y:solve.elbowTarget.y,z:solve.elbowTarget.z}};});
  const status={ready:true,nozzle:{local:{x:nozzleLocal.x,y:nozzleLocal.y,z:nozzleLocal.z},world:{x:nozzle.x,y:nozzle.y,z:nozzle.z}},hands};ikStatus={...ikStatus,hose:status};skinDirty=true;return status;
 }
 function flatFootQuaternion(side:'Left'|'Right',index:number,footYaw=parent.rotation.y){const node=bone(`${side}Foot`)?.getTransformNode(),parentNode=node?.parent as TransformNode|null;if(!node||!parentNode)return null;parentNode.computeWorldMatrix(true);const inverseBoneParent=Matrix.Identity();parentNode.getWorldMatrix().invertToRef(inverseBoneParent);const local=(axis:Vector3)=>Vector3.TransformNormal(yawAxis(axis,footYaw),inverseBoneParent).normalize(),axes=neutralFootAxes[index];return Quaternion.RotationQuaternionFromAxis(local(axes.x),local(axes.y),local(axes.z));}
 function setPlantedFootOrientation(side:'Left'|'Right',index:number,footYaw?:number){
  const node=bone(`${side}Foot`)?.getTransformNode(),flat=flatFootQuaternion(side,index,footYaw);if(!node||!flat)return;node.rotationQuaternion=flat;skinDirty=true;
  rotate(`${side}ToeBase`,0);
 }
 function solveLeg(side:'Left'|'Right',index:number,ankleTarget:Vector3,footYaw=parent.rotation.y){
  prepare();const hip=nodePoint(`${side}UpLeg`),knee=nodePoint(`${side}Leg`),ankle=nodePoint(`${side}Foot`);if(!hip||!knee||!ankle)return;
  const [upper,lower]=legLengths[index],toward=ankleTarget.subtract(hip),distance=Math.max(.001,Math.min(upper+lower-.002,toward.length())),direction=toward.normalize();
  const along=(upper*upper-lower*lower+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,upper*upper-along*along));
  const bodyForward=new Vector3(Math.sin(parent.rotation.y),0,Math.cos(parent.rotation.y)),footForward=new Vector3(Math.sin(footYaw),0,Math.cos(footYaw)),forward=bodyForward.scale(.75).add(footForward.scale(.25)).normalize(),sideAxis=Vector3.Cross(direction,forward);if(sideAxis.lengthSquared()<1e-6)sideAxis.copyFromFloats(1,0,0);sideAxis.normalize();const pole=Vector3.Cross(sideAxis,direction).normalize();
  const kneeTarget=hip.add(direction.scale(along)).add(pole.scale(height));alignBone(`${side}UpLeg`,hip,knee,kneeTarget);prepare();const kneeNow=nodePoint(`${side}Leg`),ankleNow=nodePoint(`${side}Foot`);if(kneeNow&&ankleNow)alignBone(`${side}Leg`,kneeNow,ankleNow,ankleTarget);prepare();
 }
 function constrainSwingAnkle(side:'Left'|'Right',index:number,target:Vector3){const hip=nodePoint(`${side}UpLeg`);if(!hip)return target;const reach=legLengths[index][0]+legLengths[index][1]-.005,offset=target.subtract(hip),distance=offset.length();return distance>reach&&distance>1e-6?hip.add(offset.scale(reach/distance)):target;}
 function soleOffsetWorld(index:number,footYaw=parent.rotation.y){const value=soleOffsets[index],cos=Math.cos(footYaw),sin=Math.sin(footYaw);return new Vector3(value.x*cos+value.z*sin,value.y,-value.x*sin+value.z*cos);}
 function applyGroundedPose(pose:AstronautPose,feet:GroundedFeet,grounded:boolean,motion?:GroundedMotionContext){
  if(!grounded||loadState!=='ready'){ikStatus={ready:loadState==='ready',grounded:false,feet:[]};return applyPose(pose);}
  latestPose=pose;analyticJoints=poseTargets(pose);visual.position.set(0,0,0);visual.rotation.set(0,0,0);
  for(const [name,value] of rest)if(name.includes('UpLeg')||name.endsWith('Leg')||name.includes('Foot')||name.includes('ToeBase')){const node=bone(name)?.getTransformNode();if(node)node.rotationQuaternion=value.clone();}
  prepare();const values=[feet.left,feet.right],targets=values.map(foot=>{if(foot.planted&&foot.worldAnchor)return new Vector3(foot.worldAnchor.x,foot.worldAnchor.y,foot.worldAnchor.z);const cos=Math.cos(parent.rotation.y),sin=Math.sin(parent.rotation.y),p=foot.local;return new Vector3(parent.position.x+p.x*cos+p.z*sin,parent.position.y+p.y+.0625,parent.position.z-p.x*sin+p.z*cos);}),ankleTargets=targets.map((target,i)=>target.subtract(soleOffsetWorld(i,values[i].yaw)));
  let requiredPelvisDrop=0,anticipatedPelvisDrop=0;for(let i=0;i<2;i++){const hip=nodePoint(`${i?'Right':'Left'}UpLeg`);if(!hip)continue;const target=ankleTargets[i],horizontal=Math.hypot(hip.x-target.x,hip.z-target.z),reach=legLengths[i][0]+legLengths[i][1]-.02,verticalReach=Math.sqrt(Math.max(0,reach*reach-horizontal*horizontal)),groundedAnkleY=(values[i].groundY??targets[i].y)-soleOffsetWorld(i,values[i].yaw).y,needed=Math.max(0,hip.y-(values[i].planted?target.y:groundedAnkleY)-verticalReach);if(values[i].planted)requiredPelvisDrop=Math.max(requiredPelvisDrop,needed);else if(motion&&motion.active){const phase=Math.max(0,Math.min(1,motion.phase??0)),linear=Math.max(0,Math.min(1,(phase-.55)/.35)),weight=linear*linear*(3-2*linear);anticipatedPelvisDrop=Math.max(anticipatedPelvisDrop,needed*weight);}}const requestedPelvisDrop=Math.max(requiredPelvisDrop,anticipatedPelvisDrop),targetDrop=Math.min(.18,requestedPelvisDrop),pelvisDropCapped=requestedPelvisDrop>targetDrop+1e-6;if(!motion||!motion.active)filteredPelvisDrop=targetDrop;else if(targetDrop>=filteredPelvisDrop)filteredPelvisDrop=targetDrop;else {const elapsed=Math.max(0,Math.min(.05,Number.isFinite(motion.dt)?motion.dt:0));filteredPelvisDrop+=(targetDrop-filteredPelvisDrop)*(1-Math.exp(-elapsed/.1));}const drop=filteredPelvisDrop;visual.position.y=-drop;prepare();
  for(let i=0;i<2;i++)if(!values[i].planted)ankleTargets[i]=constrainSwingAnkle(i?'Right':'Left',i,ankleTargets[i]);
  for(let iteration=0;iteration<6;iteration++){
   let converged=true;
   for(let i=0;i<2;i++){
    const side=i?'Right':'Left',foot=values[i],target=targets[i];solveLeg(side,i,ankleTargets[i],foot.yaw);
    if(foot.planted)setPlantedFootOrientation(side,i,foot.yaw);else {const clearance=Math.max(0,foot.groundY===undefined?foot.local.y:target.y-foot.groundY),linear=Math.min(1,clearance/.08),toeWeight=linear*linear*(3-2*linear),node=bone(`${side}Foot`)?.getTransformNode(),flat=node&&flatFootQuaternion(side,i,foot.yaw),base=rest.get(`${side}Foot`);if(node&&flat&&base){node.rotationQuaternion=Quaternion.Slerp(flat,base.multiply(Quaternion.RotationAxis(Vector3.Right(),foot.toe*.18)),toeWeight);skinDirty=true;}rotate(`${side}ToeBase`,foot.toe*.32*toeWeight);}prepare();const measured=worldFeet()[i],correction=new Vector3(target.x-measured.x,target.y-measured.minY,target.z-measured.z);ankleTargets[i].addInPlace(correction);if(!foot.planted)ankleTargets[i]=constrainSwingAnkle(side,i,ankleTargets[i]);if(correction.length()>.001)converged=false;
   }
   if(converged)break;
  }
  const wholeBody=applyUpperBody(motion);prepare();const measured=worldFeet(),rigPoints=Object.fromEntries(['LeftArm','LeftForeArm','LeftHand','RightArm','RightForeArm','RightHand','Spine1'].map(name=>{const point=nodePoint(name);return [name,point&&{x:point.x,y:point.y,z:point.z}];}));ikStatus={ready:true,grounded:true,pelvisDrop:drop,filteredPelvisDrop:drop,requiredPelvisDrop,anticipatedPelvisDrop,requestedPelvisDrop,pelvisDropCapped,wholeBody:{...wholeBody,rigPoints},feet:measured.map((value,i)=>({planted:values[i].planted,footYaw:values[i].yaw??parent.rotation.y,target:{x:targets[i].x,y:targets[i].y,z:targets[i].z},sole:{x:value.x,y:value.minY,z:value.z},error:Math.hypot(value.x-targets[i].x,value.minY-targets[i].y,value.z-targets[i].z)}))};return snapshot();
 }
 function snapshot():JointSnapshot[]{
  if(loadState!=='ready'||!skinMesh)return analyticJoints.map(value=>structuredClone(value));
  const boots=worldFeet();return ['Left','Right'].map((side,index)=>{const point=(name:string)=>{const node=bone(`${side}${name}`)?.getTransformNode();if(!node)return {x:0,y:0,z:0};node.computeWorldMatrix(true);const value=node.getAbsolutePosition();return {x:value.x,y:value.y,z:value.z};},hip=point('UpLeg'),knee=point('Leg'),ankle=point('Foot'),boot=boots[index];return {hip,knee,ankle,toe:point('ToeBase'),boot:{x:boot.x,y:boot.y,z:boot.z,minY:boot.minY,radius:boot.radius}};});
 }
 function worldFeet(){
  if(loadState!=='ready'||!root||!skeletonRoot){const cos=Math.cos(parent.rotation.y),sin=Math.sin(parent.rotation.y);return analyticJoints.map(({boot})=>({x:parent.position.x+(boot.x+visual.position.x)*cos+boot.z*sin,y:parent.position.y+boot.y+visual.position.y,z:parent.position.z-(boot.x+visual.position.x)*sin+boot.z*cos,minY:parent.position.y+boot.minY+visual.position.y,maxY:parent.position.y+boot.y+.16+visual.position.y,radius:boot.radius}));}
  refreshSkinnedFeet();parent.computeWorldMatrix(true);visual.computeWorldMatrix(true);root.computeWorldMatrix(true);const worldMatrices=new Map<AbstractMesh,ReturnType<AbstractMesh['getWorldMatrix']>>();for(const {mesh} of skinnedFootPoints.flat()){if(worldMatrices.has(mesh))continue;mesh.computeWorldMatrix(true);worldMatrices.set(mesh,mesh.getWorldMatrix().clone());}
  return skinnedFootPoints.map((values,index)=>{const points=values.map(({mesh,point})=>Vector3.TransformCoordinates(point,worldMatrices.get(mesh)!));if(!points.length){const side=index===0?'Left':'Right',foot=bone(`${side}Foot`)?.getAbsolutePosition(skinMesh!),toe=bone(`${side}ToeBase`)?.getAbsolutePosition(skinMesh!);if(foot&&toe)points.push(foot,toe);}if(!points.length)return {x:parent.position.x,y:parent.position.y+.2,z:parent.position.z,minY:parent.position.y+.063,maxY:parent.position.y+.4,radius:.45};const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),minZ=Math.min(...points.map(p=>p.z)),maxZ=Math.max(...points.map(p=>p.z)),x=(minX+maxX)/2,y=(minY+maxY)/2,z=(minZ+maxZ)/2;return {x,y,z,minY,maxY,radius:Math.max(...points.map(p=>Math.hypot(p.x-x,p.z-z)))};});
 }
 void SceneLoader.ImportMeshAsync(null,`${import.meta.env.BASE_URL}models/`,'j-toastie-rigged-astronaut-no-pack.glb',scene).then(result=>{
  meshes=result.meshes;for(const mesh of meshes)mesh.setEnabled(false);root=result.meshes[0];root.parent=visual;root.computeWorldMatrix(true);const rendered=result.meshes.filter(mesh=>mesh.getTotalVertices()>0);for(const mesh of rendered)mesh.computeWorldMatrix(true);const minimum=Math.min(...rendered.map(mesh=>mesh.getBoundingInfo().boundingBox.minimumWorld.y)),maximum=Math.max(...rendered.map(mesh=>mesh.getBoundingInfo().boundingBox.maximumWorld.y));modelScale=2.25/Math.max(.001,maximum-minimum);root.scaling.scaleInPlace(modelScale);root.position.y=-minimum*modelScale+.063;
  const skeleton=result.skeletons[0];if(!skeleton)throw new Error('Astronaut GLB did not contain its expected skin skeleton.');loadedSkeletons=result.skeletons;skeletonRoot=root;skinMesh=rendered.find(mesh=>mesh.skeleton===skeleton)??null;for(const value of skeleton.bones){bones.set(value.name,value);const node=value.getTransformNode();rest.set(value.name.replace('mixamorig:',''),node?.rotationQuaternion?.clone()??Quaternion.FromEulerVector(node?.rotation??Vector3.Zero()));}for(const required of ['LeftUpLeg','LeftLeg','LeftFoot','LeftToeBase','RightUpLeg','RightLeg','RightFoot','RightToeBase'])if(!bone(required))throw new Error(`Astronaut GLB is missing ${required}.`);
  for(const mesh of rendered){if(!mesh.skeleton)continue;const indices=mesh.getVerticesData(VertexBuffer.MatricesIndicesKind),weights=mesh.getVerticesData(VertexBuffer.MatricesWeightsKind);if(!indices||!weights)continue;for(let sideIndex=0;sideIndex<2;sideIndex++){const side=sideIndex===0?'Left':'Right',targets=new Set(mesh.skeleton.bones.map((value,index)=>({value,index})).filter(({value})=>value.name.includes(`${side}Foot`)||value.name.includes(`${side}Toe`)).map(({index})=>index)),selected:number[]=[];for(let vertex=0;vertex<indices.length/4;vertex++)for(let influence=0;influence<4;influence++)if(weights[vertex*4+influence]>.05&&targets.has(indices[vertex*4+influence])){selected.push(vertex);break;}if(selected.length)footVertices[sideIndex].push({mesh,indices:selected});}}
  if(footVertices.some(groups=>groups.reduce((sum,group)=>sum+group.indices.length,0)<3))throw new Error('Astronaut GLB foot skin vertices could not be identified.');for(const group of footVertices.flat())group.sampler=new SelectedSkinVertices(group.mesh,group.indices);
  for(const material of result.meshes.flatMap(mesh=>mesh.material?[mesh.material]:[])){if(material instanceof PBRMaterial){material.roughness=Math.max(.42,material.roughness??.6);material.metallic=Math.min(.18,material.metallic??0);}}
  loadState='ready';applyBones(neutral);prepare();const neutralFeet=worldFeet(),inversePlayer=Matrix.Identity();parent.getWorldMatrix().invertToRef(inversePlayer);for(let i=0;i<2;i++){const side=i?'Right':'Left',hip=nodePoint(`${side}UpLeg`),knee=nodePoint(`${side}Leg`),ankle=nodePoint(`${side}Foot`),footNode=bone(`${side}Foot`)?.getTransformNode();if(hip&&knee&&ankle){legLengths[i]=[Vector3.Distance(hip,knee),Vector3.Distance(knee,ankle)];const worldOffset=new Vector3(neutralFeet[i].x-ankle.x,neutralFeet[i].minY-ankle.y,neutralFeet[i].z-ankle.z),cos=Math.cos(parent.rotation.y),sin=Math.sin(parent.rotation.y);soleOffsets[i]=new Vector3(worldOffset.x*cos-worldOffset.z*sin,worldOffset.y,worldOffset.x*sin+worldOffset.z*cos);}if(footNode){footNode.computeWorldMatrix(true);const relative=(axis:Vector3)=>Vector3.TransformNormal(Vector3.TransformNormal(axis,footNode.getWorldMatrix()),inversePlayer).normalize();neutralFootAxes[i]={x:relative(Vector3.Right()),y:relative(Vector3.Up()),z:relative(Vector3.Forward())};}}applyBones(latestPose);for(const mesh of meshes)mesh.setEnabled(true);resolveReady();
 }).catch(error=>{loadState='error';loadError=String(error);rejectReady(error);});
 return {visual,feet:[] as AbstractMesh[],applyPose,applyGroundedPose,applyHosePose,reset:()=>{filteredPelvisDrop=0;wholeBodySpeed=0;return applyPose(neutral);},snapshot,worldFeet,verifyFootSkinning,ikStatus:()=>structuredClone(ikStatus),lookHeight:1.35,ready,modelStatus:()=>({ready:loadState==='ready',state:loadState,error:loadError||undefined,meshCount:meshes.length,skinnedMeshCount:meshes.filter(mesh=>!!mesh.skeleton).length,boneCount:bones.size,footVertexCounts:footVertices.map(groups=>groups.reduce((sum,group)=>sum+group.indices.length,0)),poseSynced:loadState==='ready'&&[...bones.values()].every(value=>!!value.getTransformNode()),bones:[...bones.keys()]})};
}
