import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {freshPath,eligibleMock,activeSessions,validatePath,reviewPass,readiness,nextAction,sessionStatus,rehearsalComplete,assessedSessions} from '../static/practice/path/model.mjs';
import {freshState,validateImport} from '../static/practice/state.mjs';
const catalog=JSON.parse(fs.readFileSync(new URL('../static/practice/curriculum.json',import.meta.url))).exercises;
const sessions=JSON.parse(fs.readFileSync(new URL('../static/practice/path/sessions.json',import.meta.url))).sessions;
const now=Date.now();
function reviewed(s,mode='peer',at=now){return {completed:true,id:s.id,mode,at,notes:'Concrete observations, calculations, assumptions and counterexamples from the actual exercise.'.repeat(2),feedback:'Reviewer saw an independent explanation and a successful follow-up trace.',scores:Object.fromEntries(s.rubric.map(r=>[r.id,2]))};}
test('catalog contains 24 runnable exercises and 12 complete timed interview sessions',()=>{assert.equal(catalog.length,24);assert.equal(sessions.length,12);assert.equal(new Set(sessions.map(s=>s.id)).size,12);for(const s of sessions){assert.equal(s.rounds.reduce((sum,r)=>sum+r.minutes,0),s.minutes);assert.ok(s.prerequisites.every(id=>catalog.some(e=>e.id===id)));assert.ok(s.rubric.length>=4);for(const r of s.rubric)assert.equal(r.anchors.length,4);assert.ok(s.followups.length>=3);}});
test('viewing or any old saved work removes a mock from the fresh pool',()=>{const e=catalog.find(e=>e.stage==='Mock');assert.ok(eligibleMock(e,{}));for(const p of [{viewedAt:now},{session:{}},{files:{}},{attempts:1}])assert.equal(eligibleMock(e,{exercises:{[e.id]:p}}),false);assert.equal(eligibleMock(e,{attempts:[{id:e.id}]}),false);});
test('old coding backups retain work; migration preserves exposure and invalidates resumed fresh credit on import',()=>{const s=freshState();s.exercises['python-refresher-1']={coldDays:[],files:{'src/python_refresher.py':'my saved code'},viewedAt:now,session:{cold:true,mode:'mock',freshMock:true,started:now}};const preserved=validateImport(s,catalog,false);assert.equal(preserved.exercises['python-refresher-1'].files['src/python_refresher.py'],'my saved code');assert.equal(preserved.exercises['python-refresher-1'].viewedAt,now);assert.equal(preserved.exercises['python-refresher-1'].session.freshMock,true);assert.equal(validateImport(s,catalog).exercises['python-refresher-1'].session.freshMock,false);});
test('solo rehearsal cannot satisfy peer evidence; a low dimension invalidates the latest review',()=>{const p=freshPath(),active=activeSessions(sessions,p.track);p.reviews=active.map(s=>reviewed(s,'solo'));assert.equal(assessedSessions(p,active,true,now).length,0);p.reviews=active.map(s=>reviewed(s));assert.equal(assessedSessions(p,active,true,now).length,active.length);p.reviews[0].scores[active[0].rubric[0].id]=1;assert.equal(assessedSessions(p,[active[0]],true,now).length,0);});
test('coding assessment qualification requires a five-round consistency window',()=>{const p=freshPath(),c=freshState(),mocks=catalog.filter(e=>e.stage==='Mock').slice(0,5),scores={correctness:2,algorithm:2,testing:2,explanation:2};for(const [i,e] of mocks.entries()){const at=now-(4-i)*86400000,passed=i>0;c.attempts.push({id:e.id,sessionId:`round-${i}`,at,passed,mockQualified:passed,freshMock:true,elapsed:e.minutes*60-(i===1?600:60)});c.exercises[e.id]={coldDays:[],assessmentReview:{errorCategory:passed?'none':'time',scores,postmortem:'The governing invariant, first consequential error, complexity, missing edge case, and sibling drill are recorded here for the next cold attempt.'.repeat(2)}};}assert.equal(readiness(p,c,sessions,now,catalog).find(g=>g.id==='blind').met,true);c.exercises[mocks[4].id].assessmentReview.scores.testing=1;assert.equal(readiness(p,c,sessions,now,catalog).find(g=>g.id==='blind').met,false);});
test('a check-box without scores and concrete evidence cannot complete a rehearsal',()=>{assert.equal(reviewPass({scores:{},notes:'done',feedback:'good'},sessions[0]),false);const p=freshPath();p.reviews=[reviewed(sessions[0])];const roundTrip=validatePath(JSON.parse(JSON.stringify(p)),sessions);assert.equal(roundTrip.reviews[0].feedback,p.reviews[0].feedback);assert.throws(()=>validatePath({},sessions));});
test('review evidence expires and active track changes requirements',()=>{const p=freshPath();p.reviews=sessions.map(s=>reviewed(s,'peer',now-31*86400000));assert.equal(readiness(p,{},sessions,now).find(g=>g.id==='loop').met,false);assert.ok(activeSessions(sessions,'both').length>activeSessions(sessions,'applied').length);});
test('fresh beginner starts guided; untouched mock recommendation launches as mock',()=>{const p=freshPath(),c=freshState();assert.equal(nextAction(p,c,catalog,sessions).id,'syntax-guided');const e=catalog.find(e=>e.stage==='Mock');assert.equal(nextAction(p,c,[e],[]).type,'mock');});
test('a later failed rehearsal invalidates earlier peer evidence until repaired',()=>{const p=freshPath(),s=sessions.find(s=>s.id==='full-loop');p.reviews=[reviewed(s,'peer',now-1000)];assert.equal(assessedSessions(p,[s],true,now).length,1);const failed=reviewed(s,'solo',now);failed.scores[s.rubric[0].id]=1;p.reviews.unshift(failed);assert.equal(assessedSessions(p,[s],true,now).length,0);});

test('completion is required and peer status agrees after later solo practice',()=>{const p=freshPath(),s=sessions[0],r=reviewed(s);assert.equal(reviewPass({...r,completed:false},s),false);p.reviews=[reviewed(s,'solo',now),reviewed(s,'peer',now-1000)];assert.equal(sessionStatus(s,p,now),'Peer-reviewed evidence');p.reviews[0].scores[s.rubric[0].id]=1;assert.equal(sessionStatus(s,p,now),'Repair and repeat');});
test('an unfinished timer cannot create readiness evidence',()=>{assert.equal(rehearsalComplete({started:now,deadline:now+60000},now),false);assert.equal(rehearsalComplete({started:now-60000,deadline:now},now),true);assert.equal(rehearsalComplete({started:now},now),false);});
