import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {freshPath,eligibleMock,activeSessions,validatePath,reviewPass,readiness,nextAction} from '../static/practice/path/model.mjs';
import {freshState,validateImport} from '../static/practice/state.mjs';
const catalog=JSON.parse(fs.readFileSync(new URL('../static/practice/curriculum.json',import.meta.url))).exercises;
const sessions=JSON.parse(fs.readFileSync(new URL('../static/practice/path/sessions.json',import.meta.url))).sessions;
const now=Date.now();
function reviewed(s,mode='peer',at=now){return {id:s.id,mode,at,notes:'Concrete observations, calculations, assumptions and counterexamples from the actual exercise.'.repeat(2),feedback:'Reviewer saw an independent explanation and a successful follow-up trace.',scores:Object.fromEntries(s.rubric.map(r=>[r.id,2]))};}
test('catalog contains 24 runnable exercises and 12 complete timed interview sessions',()=>{assert.equal(catalog.length,24);assert.equal(sessions.length,12);assert.equal(new Set(sessions.map(s=>s.id)).size,12);for(const s of sessions){assert.equal(s.rounds.reduce((sum,r)=>sum+r.minutes,0),s.minutes);assert.ok(s.prerequisites.every(id=>catalog.some(e=>e.id===id)));assert.ok(s.rubric.length>=4);for(const r of s.rubric)assert.equal(r.anchors.length,4);assert.ok(s.followups.length>=3);}});
test('viewing or any old saved work removes a mock from the fresh pool',()=>{const e=catalog.find(e=>e.stage==='Mock');assert.ok(eligibleMock(e,{}));for(const p of [{viewedAt:now},{session:{}},{files:{}},{attempts:1}])assert.equal(eligibleMock(e,{exercises:{[e.id]:p}}),false);assert.equal(eligibleMock(e,{attempts:[{id:e.id}]}),false);});
test('old coding backups retain work; migration preserves exposure and invalidates resumed fresh credit on import',()=>{const s=freshState();s.exercises['python-refresher-1']={coldDays:[],files:{'src/python_refresher.py':'my saved code'},viewedAt:now,session:{cold:true,mode:'mock',freshMock:true,started:now}};const preserved=validateImport(s,catalog,false);assert.equal(preserved.exercises['python-refresher-1'].files['src/python_refresher.py'],'my saved code');assert.equal(preserved.exercises['python-refresher-1'].viewedAt,now);assert.equal(preserved.exercises['python-refresher-1'].session.freshMock,true);assert.equal(validateImport(s,catalog).exercises['python-refresher-1'].session.freshMock,false);});
test('solo rehearsal cannot satisfy peer review gate; low dimension cannot be averaged away',()=>{const p=freshPath(),c=freshState();const active=activeSessions(sessions,p.track);p.reviews=active.map(s=>reviewed(s,'solo'));assert.equal(readiness(p,c,sessions).find(g=>g.id==='interview').met,false);p.reviews=active.map(s=>reviewed(s));assert.equal(readiness(p,c,sessions).find(g=>g.id==='interview').met,true);p.reviews[0].scores[active[0].rubric[0].id]=1;assert.equal(readiness(p,c,sessions).find(g=>g.id==='interview').met,false);});
test('fresh mock readiness requires distinct tasks AND distinct days AND recent evidence',()=>{const p=freshPath(),c=freshState();const item={passed:true,mockQualified:true,freshMock:true};c.attempts=[{...item,id:'a',at:now},{...item,id:'b',at:now}];assert.equal(readiness(p,c,sessions,now).find(g=>g.id==='mock').met,false);c.attempts[1].at=now-86400000;assert.equal(readiness(p,c,sessions,now).find(g=>g.id==='mock').met,true);c.attempts[1].freshMock=false;assert.equal(readiness(p,c,sessions,now).find(g=>g.id==='mock').met,false);c.attempts[1].freshMock=true;c.attempts[1].at=now-31*86400000;assert.equal(readiness(p,c,sessions,now).find(g=>g.id==='mock').met,false);});
test('a check-box without scores and concrete evidence cannot complete a rehearsal',()=>{assert.equal(reviewPass({scores:{},notes:'done',feedback:'good'},sessions[0]),false);const p=freshPath();p.reviews=[reviewed(sessions[0])];const roundTrip=validatePath(JSON.parse(JSON.stringify(p)),sessions);assert.equal(roundTrip.reviews[0].feedback,p.reviews[0].feedback);assert.throws(()=>validatePath({},sessions));});
test('review evidence expires and active track changes requirements',()=>{const p=freshPath();p.reviews=sessions.map(s=>reviewed(s,'peer',now-31*86400000));assert.equal(readiness(p,{},sessions,now).find(g=>g.id==='loop').met,false);assert.ok(activeSessions(sessions,'both').length>activeSessions(sessions,'applied').length);});
test('fresh beginner starts guided; untouched mock recommendation launches as mock',()=>{const p=freshPath(),c=freshState();assert.equal(nextAction(p,c,catalog,sessions).id,'syntax-guided');const e=catalog.find(e=>e.stage==='Mock');assert.equal(nextAction(p,c,[e],[]).type,'mock');});
test('a later failed rehearsal invalidates earlier peer evidence until repaired',()=>{const p=freshPath(),s=sessions.find(s=>s.id==='full-loop');p.reviews=[reviewed(s,'peer',now-1000)];assert.equal(readiness(p,{},sessions,now).find(g=>g.id==='loop').met,true);const failed=reviewed(s,'solo',now);failed.scores[s.rubric[0].id]=1;p.reviews.unshift(failed);assert.equal(readiness(p,{},sessions,now).find(g=>g.id==='loop').met,false);});
