// @ts-nocheck
export function buildAppendixRows(result) {
  return result.rows.map((row) => ({
    age: row.age,
    survival: row.survival,
    mortalityState: row.mortalityState,
    cpfPayoutMonthly: row.payoutMonthly,
    cpfPayoutAnnual: row.payoutAnnual,
    supportAnnual: row.familyTopup + row.ownTopup,
    investmentIncomeAnnual: row.grossIncomeAnnual - row.payoutAnnual - (row.familyTopup + row.ownTopup),
    basicSpendAnnual: row.basicSpendAnnual,
    discretionaryAnnual: row.discretionaryAnnual,
    medicalGross: row.medicalGross,
    insurerPaid: row.insurerPaid,
    medisavePaid: row.medisavePaid,
    medicalCash: row.medicalCash,
    emergencyExpected: row.emergencyExpected,
    emergencyBalanced: row.emergencyBalanced,
    totalSpendAnnual: row.totalSpendAnnual,
    netAnnual: row.netAnnual,
    oa: row.oa,
    ra: row.ra,
    ma: row.ma,
    bank: row.bank,
    cpfInvestments: row.cpfInvestments,
    cumulativePayouts: row.cumulativePayouts,
    premiumEquivalent: row.premiumEquivalent,
    ers: row.ers,
    bhs: row.bhs,
    taxSavingsAnnual: row.taxSavingsAnnual,
    estateEquivalent: row.estateEquivalent,
    liquidAssets: row.liquidAssets,
    basicCoverage: row.basicCoverage,
    totalCoverage: row.totalCoverage,
    liquidityCoverageMonths: (row.liquidAssets || 0) / Math.max(1, (row.basicSpendAnnual || 0) / 12),
    emergencyCoverageRatio: (row.liquidAssets || 0) / Math.max(1, row.emergencyBalanced || 0),
    medicalShareOfSpend: (row.medicalCash || 0) / Math.max(1, row.totalSpendAnnual || 0),
    cpfShareOfIncome: (row.payoutAnnual || row.cpfPayoutAnnual || 0) / Math.max(1, row.grossIncomeAnnual || 0),
    estateMinusEmergency: (row.estateEquivalent || 0) - (row.emergencyBalanced || 0),
  }));
}
