export declare function runPlan(profile: any, plan: any): {
    currentAge: number;
    frailty: {
        state: any;
        annualMedicalLoadMultiplier: number;
        annualMortalityMultiplier: number;
    };
    constraints: import("../types.js").ConstraintSet;
    familyTopups: {
        allowedTopup: number;
        modeledTaxSaved: number;
        eligible: number;
        taxSaved: number;
        name: string;
        marginalTaxRate: number;
        amount: number;
        cadence: string;
        activeYears: number;
    }[];
    interventions: {
        label: string;
        longevityDelta: number;
        costDelta: number;
    }[];
    remainingYears: number;
    modalAge: number;
    medianAge: number;
    p75Age: number;
    p90Age: number;
    cpfInitialPayout: number;
    principalCrossoverAge: number | null;
    rows: {
        cpfPayoutAnnual: number;
        basicSpendAnnual: number;
        discretionaryAnnual: number;
        medicalGross: number;
        insurerPaid: number;
        medisavePaid: number;
        medicalCash: number;
        emergencyExpected: number;
        emergencyMinimum: number;
        emergencyBalanced: number;
        emergencyConservative: number;
        totalSpendAnnual: number;
        grossIncomeAnnual: number;
        netAnnual: number;
        liquidAssets: any;
        estateEquivalent: any;
        taxSavingsAnnual: number;
        basicCoverage: boolean;
        totalCoverage: boolean;
        age: number;
        oa: number;
        sa: number;
        ra: number;
        ma: number;
        bank: number;
        cpfInvestments: number;
        familyTopup: number;
        ownTopup: number;
        payoutMonthly: number;
        payoutAnnual: number;
        cumulativePayouts: number;
        premiumEquivalent: number;
        ers: number;
        frs: number;
        bhs: number;
        extraInterestTotal: number;
        oaInterest: number;
        saInterest: number;
        raInterest: number;
        maInterest: number;
        yearOffset: number;
        survival: number;
        mortalityState: any;
    }[];
    lifestyle: {
        key: string;
        label: string;
        perTrip: number;
        trips: number;
    }[];
    emergencyGap: number;
    confidence: string;
};
