import {selectRecordingMimeType} from './recording-codec.mjs';

export type RecorderOverlay={phase:string;reason:string;choice:string;dwell:number;cursorX:number;cursorY:number;cursorVisible:boolean;cursorTracked?:boolean};
export type RecorderStatus='recording'|'paused'|'off'|'error'|'uploading';
type Options={world:HTMLCanvasElement;camera?:HTMLVideoElement;session:string|(()=>string);startedAt:number|(()=>number);record:(type:string,data:Record<string,unknown>)=>void;overlay:()=>RecorderOverlay;onStatus?:(status:RecorderStatus,detail:string)=>void;segmentMs?:number;allowed?:boolean;publicMode?:boolean;legacyHttpStore?:boolean;uploadClip?:(blob:Blob,startMs:number,endMs:number)=>Promise<boolean|void>};
const MAX_SEGMENT=1024*1024,MAX_PENDING=2*1024*1024;

export class CompactRecorder{
 private canvas=document.createElement('canvas');private ctx=this.canvas.getContext('2d')!;private stream:MediaStream|null=null;private recorder:MediaRecorder|null=null;private timer=0;private segmentTimer=0;private pendingBytes=0;private uploads=Promise.resolve();private segment=0;private active=false;private destroyed=false;private mimeType='';
 enabled=false;
 constructor(private options:Options){this.enabled=false;this.canvas.width=640;this.canvas.height=360;if(options.allowed!==false){document.addEventListener('visibilitychange',this.focusChanged);window.addEventListener('focus',this.focusChanged);window.addEventListener('blur',this.focusChanged);}}
 private emit(status:RecorderStatus,detail=''){this.options.onStatus?.(status,detail);this.options.record('recording-status',{status,detail,segment:this.segment});}
 private focused(){return !document.hidden;}
 private focusChanged=()=>{if(!this.active||!this.enabled)return;if(this.focused())this.beginSegment();else this.stopSegment('background');};
 setEnabled(value:boolean){if(this.options.allowed===false)return;this.enabled=value;if(value&&this.active&&this.focused())this.beginSegment();else if(!value)this.stopSegment('user-off');if(!this.recorder)this.emit(value?'paused':'off',value?'Ready to record when foreground':'Recording disabled');}
 start(){if(this.destroyed||this.options.allowed===false)return;this.active=true;if(this.enabled&&this.focused())this.beginSegment();else this.emit(this.enabled?'paused':'off',this.enabled?'Paused while hidden or unfocused':'Recording disabled');}
 stop(reason='walk-ended'){this.active=false;this.stopSegment(reason);if(!this.enabled)this.emit('off','Recording disabled');}
 async stopAndFlush(reason='walk-ended'){this.stop(reason);for(let i=0;i<50&&this.recorder;i++)await new Promise(resolve=>setTimeout(resolve,20));await this.uploads;}
 destroy(){this.destroyed=true;this.active=false;this.stopSegment('pagehide');document.removeEventListener('visibilitychange',this.focusChanged);window.removeEventListener('focus',this.focusChanged);window.removeEventListener('blur',this.focusChanged);}
	private codec(){const recorder=globalThis.MediaRecorder;return selectRecordingMimeType(recorder?.isTypeSupported?.bind(recorder));}
 private beginSegment(){if(this.recorder||!this.active||!this.enabled||!this.focused())return;try{
	 this.stream=this.canvas.captureStream(8);this.mimeType=this.codec();if(!this.mimeType)throw new Error('This browser cannot record a supported video format.');this.timer=window.setInterval(()=>this.draw(),125);this.draw();
 }catch(error){this.disposeStream();this.emit('error',String(error));return;}
 try{const recorder=new MediaRecorder(this.stream,{mimeType:this.mimeType,videoBitsPerSecond:300000}),chunks:Blob[]=[],startMs=Math.round(performance.now()-this.startedAt());let size=0,oversize=false;this.recorder=recorder;recorder.ondataavailable=e=>{if(!e.data.size)return;size+=e.data.size;if(size<=MAX_SEGMENT)chunks.push(e.data);else if(!oversize){oversize=true;if(recorder.state==='recording')recorder.stop();}};recorder.onerror=()=>this.emit('error','Browser video encoder failed');recorder.onstop=()=>{clearTimeout(this.segmentTimer);if(this.recorder===recorder)this.recorder=null;this.disposeStream();this.finishedSegment(chunks,size,startMs,oversize);};recorder.start(1000);this.segmentTimer=window.setTimeout(()=>this.stopSegment('segment-complete'),this.options.segmentMs??10000);this.emit('recording','Saving game + webcam on this device; no audio');}catch(error){this.recorder=null;this.disposeStream();this.emit('error',String(error));}}
 private stopSegment(reason:string){clearTimeout(this.segmentTimer);const recorder=this.recorder;if(!recorder){if(this.enabled&&this.active)this.emit('paused',reason);return;}if(recorder.state!=='inactive')recorder.stop();this.options.record('recording-segment-stop',{reason,segment:this.segment});}
 private disposeStream(){clearInterval(this.timer);this.timer=0;this.stream?.getTracks().forEach(track=>track.stop());this.stream=null;}
 private finishedSegment(chunks:Blob[],size:number,startMs:number,oversize:boolean){const id=this.segment++,endMs=Math.round(performance.now()-this.startedAt());if(!size){this.emit('error','Encoder produced an empty clip');return;}if(oversize||size>MAX_SEGMENT){this.options.record('recording-drop',{reason:'segment-oversize',bytes:size,id});this.emit('error','Clip exceeded the 1 MiB upload limit');if(this.active)this.beginSegment();return;}if(this.pendingBytes+size>MAX_PENDING){this.options.record('recording-drop',{reason:'pending-memory-limit',bytes:size,id});this.emit('error','Recording upload queue is full');if(this.active)this.beginSegment();return;}
  const blob=new Blob(chunks,{type:this.mimeType});this.pendingBytes+=size;this.emit('uploading',`Saving clip ${id} in this browser`);this.uploads=this.uploads.then(async()=>{if(this.options.uploadClip){const saved=await this.options.uploadClip(blob,startMs,endMs);if(saved===false)throw new Error('Clip was not saved');}else if(this.options.legacyHttpStore){const query=new URLSearchParams({session:this.session(),segment:String(id),startMs:String(startMs),endMs:String(endMs)});const response=await fetch(`/__recordings?${query}`,{method:'POST',headers:{'Content-Type':blob.type.split(';')[0]},body:blob,signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`Local clip store HTTP ${response.status}`);}else throw new Error('Browser recording storage is unavailable');this.options.record('recording-saved',{segment:id,startMs,endMs,bytes:size});}).catch(error=>this.emit('error',String(error))).finally(()=>{this.pendingBytes-=size;if(!this.active||!this.enabled)this.emit(this.enabled?'paused':'off',this.enabled?'Recording paused':'Recording disabled');});if(this.active&&this.enabled&&this.focused())this.beginSegment();
 }
 private session(){return typeof this.options.session==='function'?this.options.session():this.options.session;}
 private startedAt(){return typeof this.options.startedAt==='function'?this.options.startedAt():this.options.startedAt;}
 private draw(){const c=this.ctx,w=640,h=360,source=this.options.world,scale=Math.min(w/source.width,h/source.height),worldWidth=source.width*scale,worldHeight=source.height*scale,worldX=(w-worldWidth)/2,worldY=(h-worldHeight)/2;c.fillStyle='#202328';c.fillRect(0,0,w,h);try{c.drawImage(source,worldX,worldY,worldWidth,worldHeight);}catch{}const camera=this.options.camera;if(camera&&camera.readyState>=2){c.save();c.translate(624,12);c.scale(-1,1);c.drawImage(camera,0,0,192,144);c.restore();c.strokeStyle='#fff';c.strokeRect(432,12,192,144);}const o=this.options.overlay(),elapsed=Math.max(0,Math.round(performance.now()-this.startedAt()));c.fillStyle='#17191ddd';c.fillRect(12,276,616,72);c.fillStyle='white';c.font='16px system-ui';c.fillText(`${this.options.publicMode?'REC':'LOCAL REC'}  ${formatTime(elapsed)}  session ${this.session().slice(0,8)}`,24,300);c.font='14px system-ui';c.fillText(`${o.phase} · ${o.reason}`.slice(0,70),24,323);c.fillText(`choice: ${o.choice||'—'} · dwell ${Math.round(o.dwell*100)}%`,24,342);if(o.cursorVisible){c.beginPath();c.arc(worldX+o.cursorX*worldWidth,worldY+o.cursorY*worldHeight,10,0,Math.PI*2);c.strokeStyle=o.cursorTracked===false?'#999':'#ffef71';c.lineWidth=3;c.stroke();}}
}
function formatTime(ms:number){const seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}

export async function runSyntheticRecordingDiagnostic(canvas:HTMLCanvasElement,session:string,record:(type:string,data:Record<string,unknown>)=>void){
 const video=document.createElement('video');let url='';const recorder=new CompactRecorder({world:canvas,session,startedAt:performance.now(),record,legacyHttpStore:true,overlay:()=>({phase:'diagnostic',reason:'synthetic-canvas',choice:'none',dwell:0,cursorX:0,cursorY:0,cursorVisible:false}),segmentMs:1200});
 try{recorder.enabled=true;recorder.start();await new Promise(resolve=>setTimeout(resolve,1700));recorder.stop('diagnostic-complete');await new Promise(resolve=>setTimeout(resolve,900));const manifest=await fetch('/__recordings/manifest',{cache:'no-store'}).then(r=>r.json());const clip=manifest.segments.filter((s:any)=>s.session===session).at(-1);if(!clip)throw new Error('Synthetic recording was not saved');const blob=await fetch(clip.url,{cache:'no-store'}).then(r=>r.blob());url=URL.createObjectURL(blob);video.src=url;video.muted=true;await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Saved video decode timed out')),5000);video.onloadeddata=()=>{clearTimeout(timeout);resolve(null);};video.onerror=()=>{clearTimeout(timeout);reject(new Error('Saved video could not be decoded'));};video.load();});if(video.videoWidth!==640||video.videoHeight!==360)throw new Error(`Unexpected saved video metadata: ${video.videoWidth}×${video.videoHeight}`);return {bytes:blob.size,duration:video.duration,width:video.videoWidth,height:video.videoHeight,mimeType:blob.type};}finally{recorder.destroy();if(url)URL.revokeObjectURL(url);}
}
