const VERSION='forest-crew/0.1.3/grove-01',MAX_QUEUE=2*1024*1024,MAX_TELEMETRY=256*1024,MAX_DURATION=10*60*1000,MAX_SESSION=32*1024*1024;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const jsonBytes=value=>new TextEncoder().encode(JSON.stringify(value)).byteLength;
export class PlaytestSession{
 constructor({baseUrl='/',fetchImpl=globalThis.fetch,now=()=>performance.now(),onStatus=(_status)=>{},retryDelays=[250,1000],responseDrainTimeoutMs=8000}={}){this.baseUrl=new URL('api/playtests',new URL(baseUrl,globalThis.location?.href??'http://local/')).toString().replace(/\/$/,'');this.fetch=fetchImpl;this.now=now;this.onStatus=onStatus;this.retryDelays=retryDelays;this.responseDrainTimeoutMs=responseDrainTimeoutMs;this.state='undecided';this.token='';this.session='';this.started=0;this.savedBytes=0;this.queuedBytes=0;this.records=[];this.recordBytes=14;this.seq=0;this.segment=0;this.work=Promise.resolve();this.generation=0;this.error='';}
 status(extra={}){this.onStatus({state:this.state,session:this.session?safeId(this.session):'',savedBytes:this.savedBytes,queuedBytes:this.queuedBytes,error:this.error,...extra});}
 async optIn({explicitConsent=false}={}){if(this.state!=='undecided')throw new Error('A playtest choice was already made');this.state='starting';this.error='';this.status();try{const payload=explicitConsent?{consent:true,version:VERSION}:{noticeShown:true,recordingMode:'opt-out',version:VERSION};const response=await this.request(`${this.baseUrl}/sessions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},this.generation);const data=await response.json();if(this.state!=='starting')throw new Error('Playtest stopped');this.session=String(data.session||'');this.token=String(data.token||'');if(!this.session||!this.token)throw new Error('Playtest server returned an invalid session');this.maxSessionBytes=Math.min(MAX_SESSION,Number(data.maxSessionBytes)||MAX_SESSION);this.maxClipBytes=Math.min(1024*1024,Number(data.maxClipBytes)||1024*1024);this.started=this.now();this.state='recording';this.status();return data;}catch(error){if(this.state==='starting'){this.state='undecided';this.error=String(error);this.status();}throw error;}}
 optOut(){if(!['undecided','starting'].includes(this.state))return;this.generation++;this.state='opted-out';this.purge();this.status();}
 reset(){if(!['opted-out','stopped','error'].includes(this.state)||this.queuedBytes!==0)return false;this.generation++;this.state='undecided';this.error='';this.token='';this.session='';this.savedBytes=0;this.queuedBytes=0;this.seq=0;this.segment=0;this.work=Promise.resolve();this.purge();this.status();return true;}
 record(type,data={}){if(this.state!=='recording'||this.now()-this.started>=MAX_DURATION)return false;const item={seq:this.seq++,t:Math.max(0,Math.round(this.now()-this.started)),type,data:structuredClone(data)},bytes=jsonBytes(item)+(this.records.length?1:0);if(bytes+14>MAX_TELEMETRY)return false;while(this.records.length&&this.recordBytes+bytes>MAX_TELEMETRY){const removed=this.records.shift();this.recordBytes-=removed._bytes;}Object.defineProperty(item,'_bytes',{value:bytes,enumerable:false});this.records.push(item);this.recordBytes+=bytes;return true;}
 recordAt(type,data,t){if(this.state!=='recording'||!Number.isFinite(t)||t<0||t>MAX_DURATION)return false;const item={seq:this.seq++,t:Math.round(t),type,data:structuredClone(data)},size=jsonBytes(item)+(this.records.length?1:0);if(size+14>MAX_TELEMETRY)return false;while(this.records.length&&this.recordBytes+size>MAX_TELEMETRY){const removed=this.records.shift();this.recordBytes-=removed._bytes;}Object.defineProperty(item,'_bytes',{value:size,enumerable:false});this.records.push(item);this.recordBytes+=size;return true;}
 uploadClip(blob,startMs,endMs){if(this.state!=='recording')return Promise.resolve(false);const size=blob.size;if(size>this.maxClipBytes||!this.reserve(size)){this.fail('Recording upload limit reached');return Promise.resolve(false);}const generation=this.generation,id=this.segment++;this.status({uploading:true});return this.enqueue(async()=>{if(!this.live(generation))return false;await this.post(`sessions/${encodeURIComponent(this.session)}/clips/${id}?startMs=${Math.max(0,Math.round(startMs))}&endMs=${Math.max(0,Math.round(endMs))}`,{method:'POST',headers:{Authorization:`Bearer ${this.token}`,'Content-Type':blob.type.split(';')[0]},body:blob},generation);if(!this.live(generation))return false;this.savedBytes+=size;this.status();return true;},size,generation);}
 flushTelemetry(){return this.state==='recording'&&this.records.length?this.queueTelemetry():Promise.resolve(true);}
 queueTelemetry(){if(!['recording','stopping'].includes(this.state)||!this.records.length)return Promise.resolve(true);const generation=this.generation,records=this.records.splice(0),bodyText=JSON.stringify({records}),reserved=jsonBytes({records});this.recordBytes=14;if(reserved>MAX_TELEMETRY||!this.reserve(reserved)){this.fail('Telemetry upload limit reached');return Promise.resolve(false);}return this.enqueue(async()=>{if(!this.live(generation))return false;let body=bodyText,headers={Authorization:`Bearer ${this.token}`,'Content-Type':'application/json'};if(typeof CompressionStream!=='undefined'){const compressed=await new Response(new Blob([body]).stream().pipeThrough(new CompressionStream('gzip'))).blob();if(compressed.size<reserved){body=compressed;headers={...headers,'Content-Encoding':'gzip'};}}await this.post(`sessions/${encodeURIComponent(this.session)}/telemetry`,{method:'POST',headers,body},generation);if(!this.live(generation))return false;this.savedBytes+=typeof body==='string'?reserved:body.size;this.status();return true;},reserved,generation);}
 async stop(){if(!['recording','error'].includes(this.state))return;const generation=this.generation;this.state='stopping';this.status();await this.work;await this.queueTelemetry();await this.work;if(this.token&&this.session){try{await this.post(`sessions/${encodeURIComponent(this.session)}/end`,{method:'POST',headers:{Authorization:`Bearer ${this.token}`}},generation);}catch(error){this.error=String(error);}}this.generation++;this.state=this.error?'error':'stopped';this.purge();this.token='';this.work=Promise.resolve();this.status();}
 reserve(bytes){if(this.queuedBytes+bytes>MAX_QUEUE||this.savedBytes+this.queuedBytes+bytes>this.maxSessionBytes)return false;this.queuedBytes+=bytes;return true;}
 enqueue(task,reserved,generation){const queued=this.work.then(task).catch(error=>{if(this.live(generation))this.fail(String(error));return false;}).finally(()=>{if(generation!==this.generation)return;this.queuedBytes=Math.max(0,this.queuedBytes-reserved);this.status();});this.work=queued.then(()=>{});return queued;}
 purge(){this.records.length=0;this.recordBytes=14;}
 fail(message){this.error=message;this.state='error';this.status();}
 live(generation){return generation===this.generation&&['recording','error','stopping'].includes(this.state)&&Boolean(this.token);}
 async post(path,init,generation){const response=await this.request(`${this.baseUrl}/${path}`,init,generation);await drainResponse(response,this.responseDrainTimeoutMs);return response;}
 async request(url,init,generation){let last;for(let attempt=0;attempt<=this.retryDelays.length;attempt++){if(generation!==this.generation)throw new Error('Playtest stopped');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await this.fetch(url,{...init,signal:controller.signal});if(generation!==this.generation)throw Object.assign(new Error('Playtest stopped'),{nonRetryable:true});if(response.ok)return response;const error=new Error(`Playtest server HTTP ${response.status}`);if(response.status<500&&response.status!==429)throw Object.assign(error,{nonRetryable:true});last=error;}catch(error){if(error?.nonRetryable)throw error;last=error;}finally{clearTimeout(timer);}if(attempt<this.retryDelays.length)await wait(this.retryDelays[attempt]);}throw last;}
}
export function safeId(value){return String(value).slice(0,8);}

async function drainResponse(response,timeoutMs){
 const reader=response.body?.getReader();if(!reader)return;
 let timer,timedOut=false;
 const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{timedOut=true;reject(new Error('Playtest response body timed out'));},timeoutMs);});
 try{while(true){const result=await Promise.race([reader.read(),timeout]);if(result.done)break;}}
 finally{clearTimeout(timer);if(timedOut)void reader.cancel().catch(()=>{});else reader.releaseLock();}
}
